### ISSUE TITLE
Calendar() method returns Error 401 with the valid api key

### ISSUE THREAD

**Issue by sara-karami1** [jblanked/JB-News#1]
I generate an api key from the website and used the code snippet s there to test the api. Although everything was fine with get() method, but the calendar() method returns the Error:401 with the same api key. here is the output:

Error: 401
{'message': 'You have exceeded the rate limit for this API key. Please try again at 12:54 Eastern Standard Time.'}

The message is shown even at the first call.

**Comment by jblanked** [comment]
Hey Sara, 

Its because you're using the get method followed by the calendar method

If you just intend on using the Calendar, then use the Calendar method only 

Let me know if this helps,
JBlanked

**Comment by sara-karami1** [comment]
Yep, My bad ;) You're right. Thanks for the great job.

**Comment by jblanked** [comment]
Thanks friend!! I'm glad it's working for you. Have a wonderful day.
